version: '3.5'

services:
  postgres:
    container_name: mw-mp-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: mw_marketplace
      POSTGRES_PASSWORD: mw_marketplace
      PGDATA: /data/postgres
    volumes:
       - postgres:/var/www/mw_marketplace/docker-volumes/postgres
    networks:
      - mwnet
    restart: unless-stopped

  redis:
    container_name: mw-mp-redis
    image: redis:6
    volumes:
      - redis:/data
    networks:
      - mwnet
    restart: unless-stopped

  srv:
    container_name: mw-mp-srv
    image: makewebme/mw-mp-srv:latest
    networks:
      - mwnet
    restart: unless-stopped

  nginx:
    container_name: mw-mp-nginx
    image: makewebme/mw-mp-nginx:latest
    ports:
      - 127.0.0.1:80:80
    networks:
      - mwnet
    restart: unless-stopped

networks:
  mwnet:
    driver: bridge

volumes:
  postgres:
  redis:
