version: '3.5'

services:
  postgres:
    container_name: mw-mp-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: mw-mp
      POSTGRES_PASSWORD: mw-mp
      PGDATA: /data/postgres
    volumes:
       - postgres:/var/lib/postgresql/data
    networks:
      - mwnet
    restart: unless-stopped

  redis:
    container_name: mw-mp-redis
    image: redis:6
    volumes:
      - redis:/data
    networks:
      - mwnet
    restart: unless-stopped

  srv:
    container_name: mw-mp-srv
    image: makewebme/mw-mp-srv
    networks:
      - mwnet
    restart: unless-stopped

  nginx:
    container_name: mw-mp-nginx
    image: makewebme/mw-mp-nginx
    ports:
      - 80:80
    networks:
      - mwnet
    restart: unless-stopped

networks:
  mwnet:
    driver: bridge

volumes:
  postgres:
  redis:
