name: Production backend

on:
  push:
    branches:
      - 'master'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build srv image
        run: docker build -t makewebme/mw-mp-srv:latest .
