name: Delpoy backend

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build images
        run: docker-compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push postgres image
        run: docker image push makewebme/postgres:latest

      - name: Push redis image
        run: docker image push makewebme/redis:latest

      - name: Push pgadmin image
        run: docker image push makewebme/pgadmin:latest

      - name: Push srv image
        run: docker image push makewebme/srv:latest

      - name: Push nginx image
        run: docker image push makewebme/nginx:latest

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: makewebme/mw-mp-srv:latest
