name: Deploy backend

on:
  push:
    branches:
      - 'master'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build srv image
        run: docker build -t makewebme/mw-mp-srv:latest .

      - name: Build nginx image
        run: docker build -t makewebme/mw-mp-nginx:latest ./nginx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push srv image
        run: docker image push makewebme/mw-mp-srv:latest

      - name: Push nginx image
        run: docker image push makewebme/mw-mp-nginx:latest
